// Generated by gencpp from file pkg_srvs/SrvModeResponse.msg
// DO NOT EDIT!


#ifndef PKG_SRVS_MESSAGE_SRVMODERESPONSE_H
#define PKG_SRVS_MESSAGE_SRVMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_srvs
{
template <class ContainerAllocator>
struct SrvModeResponse_
{
  typedef SrvModeResponse_<ContainerAllocator> Type;

  SrvModeResponse_()
    : state(false)  {
    }
  SrvModeResponse_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvModeResponse_

typedef ::pkg_srvs::SrvModeResponse_<std::allocator<void> > SrvModeResponse;

typedef boost::shared_ptr< ::pkg_srvs::SrvModeResponse > SrvModeResponsePtr;
typedef boost::shared_ptr< ::pkg_srvs::SrvModeResponse const> SrvModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_srvs::SrvModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::pkg_srvs::SrvModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_srvs/SrvModeResponse";
  }

  static const char* value(const ::pkg_srvs::SrvModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n\
\n\
";
  }

  static const char* value(const ::pkg_srvs::SrvModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_srvs::SrvModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_srvs::SrvModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_SRVS_MESSAGE_SRVMODERESPONSE_H
