// Generated by gencpp from file pkg_srvs/SrvMode.msg
// DO NOT EDIT!


#ifndef PKG_SRVS_MESSAGE_SRVMODE_H
#define PKG_SRVS_MESSAGE_SRVMODE_H

#include <ros/service_traits.h>


#include <pkg_srvs/SrvModeRequest.h>
#include <pkg_srvs/SrvModeResponse.h>


namespace pkg_srvs
{

struct SrvMode
{

typedef SrvModeRequest Request;
typedef SrvModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvMode
} // namespace pkg_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_srvs::SrvMode > {
  static const char* value()
  {
    return "e736bf0999998d167a8e098a291bb021";
  }

  static const char* value(const ::pkg_srvs::SrvMode&) { return value(); }
};

template<>
struct DataType< ::pkg_srvs::SrvMode > {
  static const char* value()
  {
    return "pkg_srvs/SrvMode";
  }

  static const char* value(const ::pkg_srvs::SrvMode&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_srvs::SrvModeRequest> should match 
// service_traits::MD5Sum< ::pkg_srvs::SrvMode > 
template<>
struct MD5Sum< ::pkg_srvs::SrvModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_srvs::SrvMode >::value();
  }
  static const char* value(const ::pkg_srvs::SrvModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_srvs::SrvModeRequest> should match 
// service_traits::DataType< ::pkg_srvs::SrvMode > 
template<>
struct DataType< ::pkg_srvs::SrvModeRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_srvs::SrvMode >::value();
  }
  static const char* value(const ::pkg_srvs::SrvModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_srvs::SrvModeResponse> should match 
// service_traits::MD5Sum< ::pkg_srvs::SrvMode > 
template<>
struct MD5Sum< ::pkg_srvs::SrvModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_srvs::SrvMode >::value();
  }
  static const char* value(const ::pkg_srvs::SrvModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_srvs::SrvModeResponse> should match 
// service_traits::DataType< ::pkg_srvs::SrvMode > 
template<>
struct DataType< ::pkg_srvs::SrvModeResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_srvs::SrvMode >::value();
  }
  static const char* value(const ::pkg_srvs::SrvModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_SRVS_MESSAGE_SRVMODE_H
